name: Auto Checkin
on:
  # GitHub Actions 使用国际标准时间，与国内相差 16 小时，设置时注意避雷
  # 详细语法参见 https://www.runoob.com/linux/linux-comm-crontab.html
  workflow_dispatch:
  schedule:
    - cron: '0 18,21 * * *'  # 此处设置为北京时间 4:00、4:30、5:00、5:30 共尝试四次
  watch:
    types: [started]  # 也可以通过手动对项目 star 来触发
jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: checkout
        uses: 'actions/checkout@master'

      - name: set up python
        uses: 'actions/setup-python@v2'
        with:
          python-version: '3.8'

      - name: install modules
        run: 'pip install -r requirements.txt'

      - name: auto checkin
        env:
          USER: ${{ secrets.USER }}
        run: python main.py
